// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToPlan.Models;

namespace ToPlan.Migrations
{
    [DbContext(typeof(ToPlanContext))]
    partial class ToPlanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ToPlan.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreatorEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EventDate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("GastronomyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LeisureTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ListMembers")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<int>("OtherTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SportTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("EventId");

                    b.HasIndex("GastronomyTypeId");

                    b.HasIndex("LeisureTypeId");

                    b.HasIndex("OtherTypeId");

                    b.HasIndex("SportTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ToPlan.Models.GastronomyType", b =>
                {
                    b.Property<int>("GastronomyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GastronomyTypeId");

                    b.ToTable("GastronomyTypes");
                });

            modelBuilder.Entity("ToPlan.Models.LeisureType", b =>
                {
                    b.Property<int>("LeisureTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("LeisureTypeId");

                    b.ToTable("LeisureTypes");
                });

            modelBuilder.Entity("ToPlan.Models.OtherType", b =>
                {
                    b.Property<int>("OtherTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("OtherTypeId");

                    b.ToTable("OtherTypes");
                });

            modelBuilder.Entity("ToPlan.Models.SportType", b =>
                {
                    b.Property<int>("SportTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SportTypeId");

                    b.ToTable("SportTypes");
                });

            modelBuilder.Entity("ToPlan.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Preferences")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToPlan.Models.Event", b =>
                {
                    b.HasOne("ToPlan.Models.GastronomyType", "GastronomyType")
                        .WithMany("Events")
                        .HasForeignKey("GastronomyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToPlan.Models.LeisureType", "LeisureType")
                        .WithMany("Events")
                        .HasForeignKey("LeisureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToPlan.Models.OtherType", "OtherType")
                        .WithMany("Events")
                        .HasForeignKey("OtherTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToPlan.Models.SportType", "SportType")
                        .WithMany("Events")
                        .HasForeignKey("SportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToPlan.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
